# Generated by Django 5.2.8 on 2025-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0003_productdataset_storagelocation_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
