# Generated by Django 5.2.8 on 2025-12-07 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0004_product_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fruits/')),
                ('description', models.TextField(blank=True)),
                ('optimal_temp_min', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('optimal_temp_max', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('optimal_humidity_min', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('optimal_humidity_max', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('optimal_light_max', models.IntegerField(default=100)),
                ('optimal_co2_max', models.IntegerField(default=400)),
                ('shelf_life_days', models.IntegerField(default=7)),
                ('ethylene_sensitive', models.BooleanField(default=False)),
                ('chilling_sensitive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa_tz', 'M-Pesa Tanzania'), ('tigo_tz', 'Tigo Pesa Tanzania'), ('airtel_tz', 'Airtel Money Tanzania'), ('halotel_tz', 'Halotel Tanzania'), ('mtn_rw', 'MTN Rwanda'), ('airtel_rw', 'Airtel Rwanda'), ('mtn_ug', 'MTN Uganda'), ('airtel_ug', 'Airtel Uganda'), ('mpesa_ke', 'M-Pesa Kenya'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('supported_countries', models.JSONField(default=list)),
                ('supported_currencies', models.JSONField(default=list)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('transaction_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='realtimesensordata',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='realtimesensordata',
            name='condition_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='realtimesensordata',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='realtimesensordata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bika.storagelocation'),
        ),
        migrations.AlterField(
            model_name='realtimesensordata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bika.product'),
        ),
        migrations.AlterField(
            model_name='realtimesensordata',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light Intensity'), ('co2', 'CO₂ Level'), ('ethylene', 'Ethylene'), ('weight', 'Weight'), ('firmness', 'Firmness'), ('color', 'Color'), ('vibration', 'Vibration'), ('pressure', 'Pressure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_type',
            field=models.CharField(choices=[('anomaly_detection', 'Anomaly Detection'), ('sales_forecast', 'Sales Forecasting'), ('stock_prediction', 'Stock Prediction'), ('fruit_quality', 'Fruit Quality Prediction')], max_length=50),
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='FruitBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_expiry', models.DateTimeField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active Monitoring'), ('completed', 'Completed'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('initial_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bika.product')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bika.storagelocation')),
                ('fruit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.fruittype')),
            ],
            options={
                'verbose_name_plural': 'Fruit Batches',
            },
        ),
        migrations.AddField(
            model_name='realtimesensordata',
            name='fruit_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bika.fruitbatch'),
        ),
        migrations.CreateModel(
            name='FruitQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_intensity', models.DecimalField(decimal_places=2, help_text='Light in lux', max_digits=10)),
                ('co2_level', models.IntegerField()),
                ('actual_class', models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Rotten', 'Rotten')], max_length=20)),
                ('predicted_class', models.CharField(choices=[('Fresh', 'Fresh'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Rotten', 'Rotten')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ethylene_level', models.DecimalField(blank=True, decimal_places=2, help_text='Ethylene in ppm', max_digits=5, null=True)),
                ('weight_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight loss percentage', max_digits=5)),
                ('firmness', models.DecimalField(blank=True, decimal_places=2, help_text='Firmness in N', max_digits=5, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('model_version', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('fruit_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_readings', to='bika.fruitbatch')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['fruit_batch', 'timestamp'], name='bika_fruitq_fruit_b_99e267_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa (TZ)'), ('tigo_tz', 'Tigo Pesa (TZ)'), ('airtel_tz', 'Airtel Money (TZ)'), ('halotel_tz', 'Halotel (TZ)'), ('mtn_rw', 'MTN Mobile Money (RW)'), ('airtel_rw', 'Airtel Money (RW)'), ('mtn_ug', 'MTN Mobile Money (UG)'), ('airtel_ug', 'Airtel Money (UG)'), ('mpesa_ke', 'M-Pesa (KE)'), ('visa', 'Visa Card'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('mobile_money_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_money_provider', models.CharField(blank=True, max_length=50)),
                ('mobile_money_transaction_id', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_country', models.CharField(blank=True, max_length=2)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bika.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='bika_paymen_transac_d4140a_idx'), models.Index(fields=['status', 'created_at'], name='bika_paymen_status_fd747e_idx')],
            },
        ),
    ]
