# Generated by Django 5.2.9 on 2026-02-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0007_product_product_type_clientrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('order_updates', models.BooleanField(default=True)),
                ('delivery_updates', models.BooleanField(default=True)),
                ('inventory_alerts', models.BooleanField(default=True)),
                ('quality_alerts', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('app', 'Authenticator App'), ('sms', 'SMS'), ('email', 'Email')], default='app', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Two-Factor Settings',
            },
        ),
    ]
