# Generated by Django 5.2.9 on 2026-02-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0010_alter_customuser_options_customuser_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="e.g., Home, Work, Aunt's House", max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAIInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_stock_level', models.IntegerField(default=0, help_text="AI's predicted stock level in the near future.")),
                ('predicted_out_of_stock_date', models.DateField(blank=True, help_text="AI's predicted date when product might run out.", null=True)),
                ('predicted_expiry_date', models.DateField(blank=True, help_text="AI's predicted expiry date for the product.", null=True)),
                ('predicted_quality_class', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Critical', 'Critical')], help_text="AI's predicted quality class.", max_length=20, null=True)),
                ('demand_forecast_next_7_days', models.IntegerField(default=0, help_text="AI's forecasted demand for the next 7 days.")),
                ('demand_forecast_next_30_days', models.IntegerField(default=0, help_text="AI's forecasted demand for the next 30 days.")),
                ('prediction_confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence score of the latest prediction.', max_digits=5)),
                ('last_analyzed', models.DateTimeField(auto_now=True, help_text='Timestamp of the last AI analysis.')),
            ],
            options={
                'verbose_name': 'Product AI Insight',
                'verbose_name_plural': 'Product AI Insights',
            },
        ),
        migrations.AddField(
            model_name='productalert',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='The specific inventory item instance (if alert is item-specific).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bika.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='productalert',
            name='alert_type',
            field=models.CharField(choices=[('stock_low', 'Low Stock'), ('expiry_near', 'Near Expiry'), ('quality_issue', 'Quality Issue'), ('temperature_anomaly', 'Temperature Anomaly'), ('humidity_issue', 'Humidity Issue'), ('ai_anomaly', 'AI Detected Anomaly'), ('predicted_low_stock', 'Predicted Low Stock'), ('predicted_expiry', 'Predicted Expiry'), ('predicted_quality_issue', 'Predicted Quality Issue'), ('predicted_high_demand', 'Predicted High Demand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productalert',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The general product definition (optional if inventory_item is set).', null=True, on_delete=django.db.models.deletion.CASCADE, to='bika.product'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['product'], name='bika_produc_product_39992e_idx'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['inventory_item'], name='bika_produc_invento_beafa7_idx'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['alert_type'], name='bika_produc_alert_t_52ca47_idx'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['severity'], name='bika_produc_severit_35b831_idx'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['is_resolved'], name='bika_produc_is_reso_82f4ae_idx'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productaiinsights',
            name='analysis_model_used',
            field=models.ForeignKey(blank=True, help_text='The AI model used for the last analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bika.trainedmodel'),
        ),
        migrations.AddField(
            model_name='productaiinsights',
            name='inventory_item',
            field=models.OneToOneField(blank=True, help_text='The specific inventory item instance (if insight is item-specific).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='bika.inventoryitem'),
        ),
        migrations.AddField(
            model_name='productaiinsights',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The general product definition (optional if inventory_item is set).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights_for_product', to='bika.product'),
        ),
        migrations.AddField(
            model_name='productaiinsights',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='The storage location related to this insight.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights_in_location', to='bika.storagelocation'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'title')},
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['product'], name='bika_produc_product_53db27_idx'),
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['inventory_item'], name='bika_produc_invento_7ccfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['storage_location'], name='bika_produc_storage_bdbb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['predicted_out_of_stock_date'], name='bika_produc_predict_4d24d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['predicted_expiry_date'], name='bika_produc_predict_58c2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productaiinsights',
            index=models.Index(fields=['predicted_quality_class'], name='bika_produc_predict_7c43eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productaiinsights',
            unique_together={('inventory_item',), ('product', 'storage_location')},
        ),
    ]
