# Generated by Django 5.2.9 on 2026-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0011_address_productaiinsights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='api_password',
            field=models.CharField(blank=True, help_text="Specific API Password for some gateways (e.g., MTN MoMo API User's API Key)", max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='api_user',
            field=models.CharField(blank=True, help_text='Specific API User ID for some gateways (e.g., MTN MoMo)', max_length=100),
        ),
    ]
