# Generated by Django 5.2.9 on 2026-02-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0015_supplier_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='bika.supplier'),
        ),
    ]
