# Generated by Django 5.2.9 on 2026-02-13 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0017_inventorytransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text="Reason for the price change (e.g., 'Automated AI adjustment', 'Manual adjustment', 'Promotion')")),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='bika.product')),
            ],
            options={
                'verbose_name': 'Product Price History',
                'verbose_name_plural': 'Product Price History',
                'ordering': ['-change_date'],
            },
        ),
    ]
