# Generated by Django 5.2.9 on 2026-02-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0018_productpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('stock_level', 'Stock Level Prediction'), ('demand_forecast', 'Demand Forecast'), ('quality_class', 'Quality Classification'), ('expiry_date', 'Expiry Date Prediction')], max_length=50)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(help_text='e.g., MAE, RMSE, Accuracy, F1-Score', max_length=50)),
                ('metric_value', models.FloatField()),
                ('period_start', models.DateField(help_text='Start date of the prediction period.')),
                ('period_end', models.DateField(help_text='End date of the prediction period.')),
                ('notes', models.TextField(blank=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accuracy_records', to='bika.trainedmodel')),
                ('product', models.ForeignKey(blank=True, help_text='Specific product if evaluation is product-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bika.product')),
            ],
            options={
                'verbose_name': 'AI Prediction Accuracy',
                'verbose_name_plural': 'AI Prediction Accuracy',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
