# Generated by Django 5.2.9 on 2026-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0019_aipredictionaccuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='bin_number',
            field=models.CharField(blank=True, help_text='Specific bin number on the shelf.', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pallet_id',
            field=models.CharField(blank=True, help_text='ID of the pallet the item is on.', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shelf_number',
            field=models.CharField(blank=True, help_text='Specific shelf number within the storage location.', max_length=50),
        ),
    ]
