# Generated by Django 5.2.9 on 2026-02-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0020_inventoryitem_bin_number_inventoryitem_pallet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receive', 'Receive into Location'), ('put_away', 'Put Away (to shelf/bin)'), ('pick', 'Pick from Shelf/Bin'), ('pack', 'Pack for Shipment'), ('transfer_in', 'Transfer In (from another location)'), ('transfer_out', 'Transfer Out (to another location)'), ('adjust_in', 'Adjustment In'), ('adjust_out', 'Adjustment Out'), ('return', 'Customer Return'), ('damage', 'Damage/Spoilage')], max_length=50)),
                ('from_shelf', models.CharField(blank=True, max_length=50)),
                ('from_bin', models.CharField(blank=True, max_length=50)),
                ('from_pallet', models.CharField(blank=True, max_length=100)),
                ('to_shelf', models.CharField(blank=True, max_length=50)),
                ('to_bin', models.CharField(blank=True, max_length=50)),
                ('to_pallet', models.CharField(blank=True, max_length=100)),
                ('quantity_moved', models.PositiveIntegerField(default=1)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='bika.storagelocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='bika.inventoryitem')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='bika.storagelocation')),
            ],
            options={
                'verbose_name': 'Inventory Movement Log',
                'verbose_name_plural': 'Inventory Movement Logs',
                'ordering': ['-movement_date'],
            },
        ),
    ]
