# Generated by Django 5.2.9 on 2026-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0021_inventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='carrier_name',
            field=models.CharField(blank=True, help_text="Name of the shipping carrier (e.g., 'DHL', 'FedEx', 'Local Post').", max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='carrier_service_code',
            field=models.CharField(blank=True, help_text="Service code or type used by the carrier (e.g., 'EXP', 'STD', 'Priority').", max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='external_tracking_url',
            field=models.URLField(blank=True, help_text="Direct URL to the carrier's tracking page for this delivery."),
        ),
    ]
