# Generated by Django 5.2.9 on 2026-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0022_delivery_carrier_name_delivery_carrier_service_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalert',
            name='alert_type',
            field=models.CharField(choices=[('stock_low', 'Low Stock'), ('expiry_near', 'Near Expiry'), ('quality_issue', 'Quality Issue'), ('temperature_anomaly', 'Temperature Anomaly'), ('humidity_issue', 'Humidity Issue'), ('ai_anomaly', 'AI Detected Anomaly'), ('predicted_low_stock', 'Predicted Low Stock'), ('predicted_expiry', 'Predicted Expiry'), ('predicted_quality_issue', 'Predicted Quality Issue'), ('predicted_high_demand', 'Predicted High Demand'), ('movement_anomaly', 'Inventory Movement Anomaly'), ('transfer_delay', 'Inventory Transfer Delay'), ('delivery_delay', 'Delivery Delay'), ('driver_issue', 'Driver Issue Alert')], max_length=50),
        ),
    ]
