# Generated by Django 5.2.9 on 2026-02-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0023_alter_productalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productalert',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='bika.delivery'),
        ),
    ]
