# Generated by Django 5.2.9 on 2026-02-13 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0024_productalert_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the coupon.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the coupon (e.g., '10% off all fruits').")),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Value of the discount (e.g., 10 for 10%, 5.00 for $5 off).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used overall.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required to use this coupon.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='bika.productcategory')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='bika.product')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
