# Generated by Django 5.2.8 on 2026-02-13 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0026_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the marketing campaign', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the campaign objectives and content')),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('sms', 'SMS Campaign'), ('in_app', 'In-App Notification'), ('push', 'Push Notification'), ('banner', 'Website Banner')], default='email', max_length=20)),
                ('target_segment', models.CharField(choices=[('all_users', 'All Users'), ('customers', 'All Customers'), ('vendors', 'All Vendors'), ('new_users', 'New Users (last 30 days)'), ('inactive_users', 'Inactive Users (last 90 days)'), ('high_value_customers', 'High-Value Customers'), ('cart_abandoners', 'Cart Abandoners'), ('category_interest', 'Users Interested in Specific Categories')], default='all_users', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Subject line for email/push notifications', max_length=255)),
                ('content', models.TextField(help_text='Main content of the campaign message (e.g., email body, in-app text)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
