"""
Django settings for bika_project project.

Generated by 'django-admin startproject' using Django 5.2.8
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings
SECRET_KEY = 'django-insecure-bika-project-secret-key-2025-change-this-in-production'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '172.16.19.60']
CSRF_TRUSTED_ORIGINS = [
  'http://localhost:8000',
  'http://127.0.0.1:8000',
  'http://0.0.0.0:8000',
  'http://172.16.16.195:8000',
]



# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Local apps
    'bika.apps.BikaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bika.middleware.SecurityHeadersMiddleware',
    'bika.middleware.SessionTimeoutMiddleware',
    'bika.middleware.RoleBasedAccessMiddleware',

]

ROOT_URLCONF = 'bika_project.urls'
WSGI_APPLICATION = 'bika_project.wsgi.application'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'bika.context_processors.site_info',
                'bika.context_processors.cart_details',
                'bika.context_processors.user_profile_info',
            ],
        },
    },
]



# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'bika' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTH_USER_MODEL = 'bika.CustomUser'

LOGIN_URL = 'bika:login'
LOGIN_REDIRECT_URL = 'bika:home'
LOGOUT_REDIRECT_URL = 'bika:home'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abeliniyigena@gmail.com'
EMAIL_HOST_PASSWORD = 'MUGO12ruku__'
DEFAULT_FROM_EMAIL = 'Bika <noreply@bika.com>'

# Session Configuration
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://0.0.0.0:8000',
    'http://172.16.16.195:8000',
]

# Security Settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Bika Application Specific Settings
BIKA_SETTINGS = {
    'APP_NAME': 'Bika',
    'APP_DESCRIPTION': 'AI-Powered Fruit Quality Monitoring & E-commerce Platform',
    'APP_VERSION': '1.0.0',
    'SUPPORT_EMAIL': 'support@bika.com',
    'SALES_EMAIL': 'sales@bika.com',
    'ADMIN_EMAIL': 'admin@bika.com',
    
    # Product Settings
    'MAX_PRODUCT_IMAGES': 10,
    'DEFAULT_STOCK_THRESHOLD': 5,
    'DEFAULT_TAX_RATE': 0.18,  # 18% VAT
    
    # Order Settings
    'SHIPPING_COST': 5000,  # In default currency
    'FREE_SHIPPING_THRESHOLD': 100000,  # Free shipping above this amount
    'ORDER_PROCESSING_DAYS': 1,
    'DELIVERY_ESTIMATE_DAYS': 3,
    
    # Fruit Quality Monitoring
    'DEFAULT_FRUIT_SHELF_LIFE': 7,  # days
    'QUALITY_CHECK_INTERVAL_HOURS': 24,
    'CRITICAL_TEMP_THRESHOLD': 10,  # °C
    'CRITICAL_HUMIDITY_THRESHOLD': 95,  # %
}

# Bika AI Settings
BIKA_AI_SERVICE_TYPE = 'enhanced'
BIKA_AI_MODEL_DIR = os.path.join(MEDIA_ROOT, 'fruit_models')
BIKA_AI_CACHE_TIMEOUT = 3600  # 1 hour
BIKA_AI_MAX_PREDICTIONS_PER_BATCH = 1000

# Create required directories
required_dirs = [
    MEDIA_ROOT,
    MEDIA_ROOT / 'products',
    MEDIA_ROOT / 'categories',
    MEDIA_ROOT / 'profiles',
    MEDIA_ROOT / 'business_logos',
    MEDIA_ROOT / 'trained_models',
    MEDIA_ROOT / 'datasets',
    MEDIA_ROOT / 'fruit_datasets',
    MEDIA_ROOT / 'fruit_models',
    MEDIA_ROOT / 'services',
    MEDIA_ROOT / 'testimonials',
    MEDIA_ROOT / 'fruits',
    MEDIA_ROOT / 'site' / 'logo',
    MEDIA_ROOT / 'site' / 'favicon',
    STATIC_ROOT,
    BASE_DIR / 'logs',
]

for directory in required_dirs:
    os.makedirs(directory, exist_ok=True)

# Custom error handlers
handler404 = 'bika.views.handler404'
handler500 = 'bika.views.handler500'
handler403 = 'bika.views.handler403'
handler400 = 'bika.views.handler400'

# Only add optional apps if they are installed
try:
    INSTALLED_APPS.insert(0, 'crispy_forms')
    CRISPY_TEMPLATE_PACK = "bootstrap4"
except ImportError:
    pass

try:
    INSTALLED_APPS.append('django_extensions')
except ImportError:
    pass

try:
    INSTALLED_APPS.append('mathfilters')
except ImportError:
    pass
# Session settings for timeout middleware
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CSP Settings (if using SecurityHeadersMiddleware)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'